[features]
detailed_timers = []
show_char_stream = []
show_tokens = []
show_headers = []
show_ast = []
show_eval = []
show_codegen = []
show_hir = []
show_lir = []
show_borrow_checker = []

[package]
name = "beanstalk"
version = "0.0.1-alpha"
edition = "2024"

[[bin]]
name = "bst"
path = "src/main.rs"

[dependencies]
fs_extra = "1.3.0"
colour = "2.1.0"
wasmparser = "0.244.0"
wasm-encoder = "0.244.0"

[dev-dependencies]

[profile.release]
debug = true