[features]
detailed_timers = []
show_char_stream = []
show_tokens = []
show_ast = []
show_eval = []
show_ir = []
show_codegen = []
show_wir = []
show_borrow_checker = []
wasix_native_functions = []
wasix_enhanced_io = []
verbose_codegen_logging = []

[package]
name = "beanstalk"
version = "0.0.1-alpha"
edition = "2024"

[[bin]]
name = "bst"
path = "src/main.rs"

[dependencies]
fs_extra = "1.3.0"
colour = "2.1.0"
wat = "1.235.0"
wasmparser = "0.238.1"
rayon = "1.10.0"
wasmer = "6.1.0-rc.5"
wasm-encoder = "0.238.1"
wasmer-types = "6.1.0-rc.5"
wasmer-wasix = "0.601.0-rc.5"
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
serde_json = "1.0.145"
